name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure dist folder exists
      - name: Create dist folder
        run: mkdir -p dist

      # Step 3: Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          palette: github-dark

      # Step 4: Push generated snake.svg to output branch manually
      - name: Push snake.svg to output branch
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git fetch origin output || git checkout --orphan output
          git checkout output || git checkout --orphan output
          git reset --hard
          cp -f dist/snake.svg .
          git add snake.svg
          git commit -m "Update snake.svg"
          git push -u origin output --force
